nodes:
  # Indexer server nodes
  indexer:
    - name: node-1
      ip: 192.168.64.135

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:

  # Dashboard node
  dashboard:
